language: go
go:
  - tip
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls
script:
  - go test -v -coverprofile=.coverprofile ./sdp
  - go test -bench=. ./sdp
  - $HOME/gopath/bin/goveralls -coverprofile=.coverprofile -service=travis-ci
  - $HOME/gopath/bin/golint ./...
